<!DOCTYPE html>
<!--
 * OpenBoleto - Geração de boletos bancários em PHP
 *
 * LICENSE: The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify,
 * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies
 * or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-->
<html lang="pt-BR">
<head>
	<meta charset="UTF-8">
	<title><?php echo $cedente; ?></title>
	<style type="text/css">
		/* Embed the CSS content here */
		<?php include $resource_path . '/css/styles.css' ?>
	</style>
</head>
<body>

<div style="width: 666px">
	<?php if ( $instrucoesImpressao ): ?>
		<div class="noprint info">
			<h2>Instruções de Impressão</h2>
			<ul>
				<li>Imprima em impressora jato de tinta (ink jet) ou laser em qualidade normal ou alta (Não use modo econômico).</li>
				<li>Utilize folha A4 (210 x 297 mm) ou Carta (216 x 279 mm) e margens mínimas à esquerda e à direita do formulário.</li>
				<li>Corte na linha indicada. Não rasure, risque, fure ou dobre a região onde se encontra o código de barras.</li>
				<li>Caso não apareça o código de barras no final, pressione F5 para atualizar esta tela.</li>
				<li>Caso tenha problemas ao imprimir, copie a sequencia numérica abaixo e pague no caixa eletrônico ou no internet banking:</li>
			</ul>
			<span class="header">Linha Digitável: <?php echo $linha_digitavel; ?></span>
			<?php if ( $valor_documento ) : ?><span class="header">Valor: R$ <?php echo $valor_documento; ?></span><?php endif ?>
			<?php if ( $pagamento_minimo ) : ?><span class="header">Pagamento mínimo: R$ <?php echo $pagamento_minimo; ?></span><?php endif ?>
			<br>

			<div class="linha-pontilhada" style="margin-bottom: 20px;">Recibo do sacado</div>
		</div>
	<?php endif; ?>
	<div class="info-empresa">
		<?php if ( $logotipo ) : ?>
			<div style="display: inline-block;">
				<img alt="logotipo" src="<?php echo $logotipo; ?>"/>
			</div>
		<?php endif ?>
		<div style="display: inline-block; vertical-align: super;">
			<div><strong><?php echo $cedente; ?></strong></div>
			<div><?php echo $cedente_cpf_cnpj; ?></div>
			<div><?php echo $cedente_endereco1; ?></div>
			<div><?php echo $cedente_endereco2; ?></div>
		</div>
	</div>
	<br>

	<?php include( 'partials/recibo-pagador.phtml' ) ?>

	<!-- Ficha de compensação -->
	<?php include( 'partials/ficha-de-compensacao.phtml' ) ?>
</div>
</body>
</html>
