<!DOCTYPE html>
<!--
 * OpenBoleto - Geração de boletos bancários em PHP
 *
 * LICENSE: The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify,
 * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies
 * or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-->
<html lang="pt-BR">
<head>
	<meta charset="UTF-8">
	<title><?php echo $cedente; ?></title>
	<style type="text/css">
		/* Embed the CSS content here */
		<?php include $resource_path . '/css/carta.css' ?>
		<?php include $resource_path . '/css/styles.css' ?>
	</style>
</head>
<body>

<div class="panel">
	<div class="logo">
		<img src="<?php echo $logo_banco ?>" alt="Logo" title="Logo"/>
	</div>
	<div class="header" >
		<h1>Boleto CrediSIS</h1>
	</div>
	<div class="content">
		<div class="endereco">
			<span class="documento">3532</span>
			<br>
			<span class="nome"><?php echo $sacado ?></span>
			<br>
			<span><?php echo $sacado_endereco1 ?></span>
			<br>
			<span><?php echo $sacado_endereco2 ?></span>
		</div>
	</div>
</div>

<hr>

<div>
	<?php include( 'partials/recibo-pagador.phtml' ) ?>

	<!-- Ficha de compensação -->
	<?php include( 'partials/ficha-de-compensacao.phtml' ) ?>
</div>

</body>
</html>
